// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Site_Baras_Andrei.Data;

#nullable disable

namespace Site_Baras_Andrei.Migrations
{
    [DbContext(typeof(Site_Baras_AndreiContext))]
    [Migration("20230118142914_IngredienteProdus")]
    partial class IngredienteProdus
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Site_Baras_Andrei.Models.Ingredient", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("NumeIngredient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("Site_Baras_Andrei.Models.Produs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("DenumireProdus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IngredientID")
                        .HasColumnType("int");

                    b.Property<decimal>("ValoriNutritionale")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("IngredientID");

                    b.ToTable("Produs");
                });

            modelBuilder.Entity("Site_Baras_Andrei.Models.Produs", b =>
                {
                    b.HasOne("Site_Baras_Andrei.Models.Ingredient", "Ingredient")
                        .WithMany("Produse")
                        .HasForeignKey("IngredientID");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Site_Baras_Andrei.Models.Ingredient", b =>
                {
                    b.Navigation("Produse");
                });
#pragma warning restore 612, 618
        }
    }
}
